version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/shared_files/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      dobot_network:
        ipv4_address: 172.10.0.2

  uwsgi:
    container_name: uwsgi
    build:
      context: ./uwsgi
    volumes:
      - ./uwsgi/shared_files/uwsgi.ini:/app/config/uwsgi.ini
      - ../app/src/main.py:/app/main.py
    networks:
      dobot_network:
        ipv4_address: 172.10.0.3

networks:
  dobot_network:
    name: dobot_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
