version: "3.5"

services:
  dobot:
    container_name: dobot
    build:
      context: ./dobot
    volumes:
      - ../app/src/:/app/
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      dobot_network:
        ipv4_address: 172.10.0.3

networks:
  dobot_network:
    name: dobot_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
