version: "3.5"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/shared_files/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "29999:29999"
      - "30003:30003"
    networks:
      dobot_network:
        ipv4_address: 172.10.0.2

  dobot:
    container_name: dobot
    build:
      context: ./dobot
    volumes:
      - ../app/src/:/app/
    networks:
      dobot_network:
        ipv4_address: 172.10.0.3

networks:
  dobot_network:
    name: dobot_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
