version: "3.5"

services:
  test_dobot:
    container_name: test_dobot
    build:
      context: ./dobot
    volumes:
      - ../app/src/:/app/src/
      - ../app/tests/:/app/tests/
    environment:
      - PYTHONUNBUFFERED=1
