name: lint

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "app/src app/tests"
          use-pylint: false
          use-black: false
          extra-mypy-options: "--ignore-missing-imports"
          extra-pycodestyle-options: "--max-line-length=88"
          extra-flake8-options: "--max-line-length 88"
